//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LecteurAudio.rc
//
#define ID_AVANCEMENT_PISTE_TIMER       1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LecteurAudio_DIALOG         102
#define IDC_STATIC_LIBAVANCEMENT        102
#define IDC_LECTEUR                     102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       132
#define IDB_BITMAP1                     146
#define IDB_BITMAP2                     147
#define IDB_BITMAP3                     148
#define IDB_BITMAP4                     149
#define IDB_BITMAP9                     154
#define IDB_BITMAP10                    155
#define IDB_BITMAP11                    156
#define IDB_BITMAP12                    157
#define IDB_BITMAP25                    170
#define IDB_BITMAP26                    171
#define IDB_BITMAP27                    172
#define IDB_BITMAP28                    173
#define IDB_BITMAP29                    174
#define IDB_BITMAP30                    175
#define IDB_BITMAP31                    176
#define IDB_BITMAP32                    177
#define IDB_BITMAP33                    178
#define IDB_BITMAP34                    179
#define IDB_BITMAP35                    180
#define IDB_BITMAP36                    181
#define IDB_BITMAP37                    182
#define IDB_BITMAP5                     216
#define IDB_BITMAP6                     217
#define IDB_BITMAP7                     218
#define IDB_BITMAP8                     219
#define IDB_BITMAP13                    220
#define IDB_BITMAP14                    221
#define IDB_BITMAP15                    222
#define IDB_BITMAP16                    223
#define IDB_BITMAP17                    224
#define IDB_BITMAP18                    225
#define IDB_BITMAP19                    226
#define IDB_BITMAP20                    227
#define IDB_BITMAP21                    228
#define IDB_BITMAP22                    229
#define IDB_BITMAP23                    230
#define IDB_BITMAP24                    231
#define IDB_BITMAP38                    232
#define IDB_BITMAP39                    233
#define IDB_BITMAP40                    234
#define IDB_BITMAP41                    235
#define IDB_BITMAP42                    236
#define IDB_BITMAP43                    237
#define IDB_BITMAP44                    238
#define IDB_BITMAP45                    239
#define IDB_BITMAP46                    240
#define IDB_BITMAP47                    241
#define IDB_BITMAP48                    242
#define IDB_BITMAP49                    243
#define IDB_BITMAP50                    244
#define IDB_BITMAP51                    245
#define IDB_BITMAP52                    246
#define IDB_BITMAP53                    247
#define IDB_BITMAP54                    248
#define IDB_BITMAP55                    249
#define IDB_BITMAP56                    250
#define IDB_BITMAP57                    251
#define IDB_BITMAP58                    252
#define IDB_BITMAP59                    253
#define IDB_BITMAP60                    254
#define IDB_BITMAP61                    255
#define IDB_BITMAP62                    256
#define IDB_BITMAP63                    257
#define IDB_BITMAP64                    258
#define IDB_BITMAP65                    259
#define IDB_BITMAP66                    260
#define IDB_BITMAP67                    261
#define IDB_BITMAP68                    262
#define IDB_BITMAP69                    263
#define IDB_BITMAP70                    264
#define IDB_BITMAP71                    265
#define IDB_BITMAP72                    266
#define IDB_BITMAP73                    267
#define IDB_BITMAP74                    268
#define IDC_LIST1                       1000
#define ID_BTN_AIDE                     1002
#define ID_BTN_JOUER                    1003
#define ID_BTN_QUITTER                  1004
#define ID_BTN_AJOUTER_UN_TITRE         1005
#define ID_BTN_PAUSE                    1007
#define ID_BTN_SUIVANT                  1008
#define ID_BTN_PRECEDENT                1009
#define ID_BTN_ARRET                    1010
#define ID_BTN_ENLEVER_LE_TITRE_SELECTIONNE 1011
#define IDC_VOLUME                      1014
#define IDC_STATIC_LIBVOLUME            1015
#define IDC_AVANCEMENT                  1020
#define IDC_BTN_SAUVEGARDER             1023
#define IDC_BTN_CHARGER                 1025
#define IDC_LIST2                       1026
#define IDC_PASSER_AUTO_SUIV            1027
#define IDC_LIB_AVANCEMENT              1028
#define IDC_BTN_ARRIERE                 1030
#define IDC_BTN_AVANT                   1031
#define IDC_CHECK1                      1034
#define IDC_LECTURE_BOUCLE              1034
#define IDC_CHECK2                      1036
#define IDC_LECTURE_HASARD              1036
#define ID_BTN_RETIRER_TOUT             1037
#define IDC_BTN_RETIRER_TOUT            1037
#define IDC_BTN_TRIER_AZ                1038
#define IDC_BTN_TRIER_ZA                1039
#define IDC_BTN_UP                      1040
#define IDC_BTN_DOWN                    1041
#define IDC_BUTTON1                     1042
#define IDC_LIST3                       1043

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        269
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
